right side bar frontend basic
UCLA-Noms/class-graph pull request #2
Opened 2023-11-24 18:46 UTC by henrywangzh

2023-11-24 18:58 UTC, olpai approved these changes
lgtm

2023-11-24 18:58 UTC, justinsheu approved these changes
lgtm

2023-11-25 00:15 UTC, jason2020 requested changes
Changes seem fine, but need to fix CI:CD

2023-11-25 00:15 UTC, jason2020 commented on src/App.tsx
This is where the Github Actions for the CD build is failing, please look into the following comments by GitHubActions.

2023-11-25 00:15 UTC, jason2020 commented on src/components/ClassGraph.tsx
There are many TS-related typing errors that are breaking the build

2023-11-25 01:59 UTC, jason2020 approved these changes
LGTM

2023-11-25 02:00 UTC, merged